version: '2'
services:
  app:
    build: .
    image: knight-rider
    container_name: knight-rider
    restart: always
    ports:
     - "3000:3000"
     - "80:80"
     - "443:443"
    expose:
     - "3000"
     - "80"
     - "443"
    volumes:
     - ../knight-rider:/app
     - ./docker-database.yml:/app/config/database.yml
    volumes_from:
     - bundle
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres.local
      - redis:redis.local
    env_file:
      - .env
  bundle:
    image: knight-rider
    container_name: bundle
    command: echo I am a little data container...
    volumes:
      - /bundle
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
     - "5432:5432"
    expose:
     - "5432"
    volumes:
     - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
     - "6379:6379"
    expose:
     - "6379"
    volumes:
      - redis:/var/lib/redis/data
volumes:
  redis:
  postgres:
